### ISSUE TITLE
When I have used a powered USB3.0 HUB to connect two ZED CAMERA, it should be something incorrect.

### ISSUE THREAD

**Issue by wkoa** [stereolabs/zed-multi-input#5]
I am trying to use a Powered USB3.0 HUB to connect two ZED CAMERA. But when I run the standard example CAMERA_STREAMING SENDER to enable two streaming with two different port(30000 and 32000), one of those two zed camera will be closed off.
**So is it not possible to connect two ZEDs in one USB HUB?**
P.s Sometimes I can run two ZED simultaneously but in the receiver side, I can only get one streaming which was opened later.

**Comment by austinlucaslake** [comment]
I'm having a similar issue. It's been some time since you posted this issue. I am hoping you may have some insight that could help resolve my issues.

My current setup is a ZED and a ZED2i on a NVIDIA Jetson AGX Xavier. The AGX Xavier is currently running Ubuntu 18.04 and ZED SDK 3.6. Both ZED cameras are connected to a USB 3.0 Hub, which then plugs into the USB-C port on the back of the AGX Xavier. I am trying to run both camera's simultaneously, however only one of the two cameras is detected at a time. Specifically, the ZED2i is the camera that is detected and shows its camera/depth feed.

Could you explain what steps you took to get two ZED simultaneously?

Thank you.
